# Generated by Django 5.1.6 on 2025-02-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ROLL_NUM', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Job_Role', models.CharField(max_length=255)),
                ('DateofInterview', models.CharField(max_length=50)),
                ('TimeofInterview', models.CharField(max_length=50)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
