# Generated by Django 5.1.6 on 2025-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_delete_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DateofInterview',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='TimeofInterview',
            field=models.TimeField(),
        ),
    ]
